### PR TITLE
Expect addr like ::1 in hasPort util

### PR DESCRIPTION
**Pull request by sakateka**
resolv.conf support v6 addr without '[]', hasPort should handle this case.

### CODE REVIEW

**Comment by sakateka** [comment]
@slackpad Please take a look.

**Comment by sakateka** [comment]
Hi, what can be done to make this PR have merged?

**Comment by sakateka** [comment]
@ryanuber,  please take a look.

**Comment by sakateka** [comment]
Hello, write any reply.

**Comment by slackpad** [comment]
@sakateka sorry for the delay on that one!

**Pull request merged**
