### PR TITLE
Adds more time to check in an attempt to make unit test less flaky.

### PR DESCRIPTION
**Pull request by slackpad**
This timing was a little tight. Lemme know if it still flakes on you.

### CODE REVIEW

**Comment by ryanuber** [comment]
Oh computers.... this branch failed on my 3rd attempt on line 173:

```
--- FAIL: TestMemberList_ProbeNode_FallbackTCP-4 (0.02s)
	state_test.go:173: bad seqno 0
```

**Comment by slackpad** [comment]
Hmm I haven't seen that one before. Let me see if I can get that to happen locally.

**Comment by slackpad** [comment]
Looking more carefully at the logic for the random probe it looks like it can give you less than 2 peers if you are unlucky. Changed the logic to make sure we got at least one indirect probe, which should be guaranteed by the algorithm no matter what. I was able to run this in a loop for a few minutes with no failures.

Widened the timing a little more, too, just to be safe.

**Comment by slackpad** [comment]
This one should be good to go if you have a sec.

**Comment by ryanuber** [comment]
LGTM, and passing consistently now. :+1:

**Pull request merged**
