### PR TITLE
Fix a data race in suspicion Confirm

### PR DESCRIPTION
**Pull request by lodthe**
Maps are not thread-safe, so data access must be synchronized.

### CODE REVIEW

**Comment by eculver** [comment]
I'm curious how you discovered this problem given that we are currently running tests with the `--race` flag? Would you mind sharing some of your process/context here?

**Comment by lodthe** [comment]
> I'm curious how you discovered this problem given that we are currently running tests with the `--race` flag? Would you mind sharing some of your process/context here?
I didn't use memberlist somewhere, I was just exploring the implementation of the algorithm. 

It just caught my eye that some modifications are atomic (e.g., when modifying the number of confirmations), but the map modifications are not synchronized. In my mind, modifications of both of these variables must be either synchronized or not.

**Review by dnephin — COMMENTED** [review]
Thank you for your interest in improving memberlist!

From my reading of the code, the only place this `suspicion.Confirm` method is called is from here:

https://github.com/hashicorp/memberlist/blob/923f1b205dd4653f2ea35e1c9531088e52053aa0/state.go#L1140-L1159

At the top of that function the `nodeLock` is held. I think that means that in practice this is not a data race. There is a lock, but it is being managed by the caller to this function.

I think it might be valuable to document this assumption in the code, to prevent changes that might break the assumption, but I don't think we want to introduce a lock for this map if it's never accessed concurrently.

**Comment by dnephin** [comment]
Thanks again for the PR! We appreciate the desire to improve memberlist. Since it seems this is safe in practice we are going to close this PR.

**Pull request closed without merging**
